# NumPy 基本例
このノートブックではNumPyの基本的な使い方を紹介します。

In [1]:
import numpy as np

## 1次元配列の作成

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", array_1d)

1D array: [1 2 3 4 5]


## 2次元配列(行列)の作成

In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", array_2d)

2D array:
 [[1 2 3]
 [4 5 6]]


## 配列の属性

In [4]:
print("Shape of array_2d:", array_2d.shape)
print("Data type of array_1d:", array_1d.dtype)

Shape of array_2d: (2, 3)
Data type of array_1d: int64


## 基本的な演算

In [5]:
sum_result = array_1d + 10
print("array_1d + 10:", sum_result)
product_result = array_1d * 2
print("array_1d * 2:", product_result)

array_1d + 10: [11 12 13 14 15]
array_1d * 2: [ 2  4  6  8 10]


## 配列同士の演算

In [6]:
array_b = np.array([10, 20, 30, 40, 50])
combined = array_1d + array_b
print("array_1d + array_b:", combined)

array_1d + array_b: [11 22 33 44 55]


## 平均の計算

In [7]:
mean_val = array_1d.mean()
print("Mean of array_1d:", mean_val)

Mean of array_1d: 3.0


## 形状の変更

In [8]:
reshaped = np.reshape(array_1d, (5, 1))
print("Reshaped array_1d to 5x1:\n", reshaped)

Reshaped array_1d to 5x1:
 [[1]
 [2]
 [3]
 [4]
 [5]]


## 連続した数値の生成

In [9]:
range_arr = np.arange(0, 10, 2)
print("np.arange(0, 10, 2):", range_arr)

np.arange(0, 10, 2): [0 2 4 6 8]


## 等間隔の数値列

In [10]:
linspace_arr = np.linspace(0, 1, 5)
print("np.linspace(0, 1, 5):", linspace_arr)

np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
